### ISSUE TITLE
Sync with upstream

### ISSUE THREAD

**Issue by filipnavara** [hez2010/sizoscopeX#1]
It would be amazing if the upstream changes were incorporated (eg. https://github.com/MichalStrehovsky/sizoscope/commit/3090785663389fcb80b5801c9659b0b43a570f49). Not sure if you prefer to rebase, or if a merge PR would be welcome.

**Comment by hez2010** [comment]
Sorry for the delay, I just returned from vacation. 
Yes. I'm definitely willing to sync the changes from upstream. 
A merge PR is welcome.

**Comment by hez2010** [comment]
Fixed with the latest commit.

**Comment by filipnavara** [comment]
> Fixed with the latest commit.

Thanks for beating me to it!
