### ISSUE TITLE
Make it work in the Browser

### ISSUE THREAD

**Issue by maxkatz6** [hez2010/sizoscopeX#2]
From my understanding, this tool doesn't really require much file system access that can't be replaced with file pickers or dragndrop. Meaning, it should work just fine in the browser.
1. Split a single project into Shared, Desktop and Browser projects.
2. Duplicate windows as views and use single-page navigation (either only on browser or everywhere).
3. Make sure all APIs used here are async (i.e. including Stream and file operations, all should be async and async disposable).
4. No threads or thread-pool (can be kept if OperatingSystem.IsBrowser = false).
5. Deploy to the github pages or something like this.
6. Enjoy tool without downloading or updating it every once and a while

It also seems current code uses TryGetLocalPath instead of OpenReadAsync. For mstat file picker it should be easy to replace, but I don't think we can easily get "scan.dgml.xml" file from the same folder having only mstat (i.e. one option is to call file.GetPraent().GetItems() and expect it to work in browser). In the worst case can be replaced with a second picker.

Not sure if PEReader works with the browser, but it could. To compare, Cecil works just fine.

**Comment by maxkatz6** [comment]
I can help with some steps, but can't promise I will have time to code it this week.

**Comment by hez2010** [comment]
I made an initial attempt and pushed the work to master branch, but encountered a couple of issues against SynchorizationContext, async vs unsafe and etc. 
I'm running out of time budget so I will leave the browser project as is. If anyone has any interest, feel free to pick it up and make it work in the browser.

**Comment by maxkatz6** [comment]
@hez2010 did some changes, seems to work fine for mstat only files, but fails with out of memory on XML files.
https://github.com/hez2010/sizoscopeX/pull/3

**Comment by hez2010** [comment]
Closing as completed.

**Comment by hez2010** [comment]
The website is on live: https://hez2010.github.io/sizoscopeX/
